   285.7ms (setup:755): 2025-08-12 09:31:13
   285.9ms (setup:756): /usr/bin/pipx install OPi.GPIO
   286.0ms (setup:757): pipx version is 1.1.0
   286.1ms (setup:758): Default python interpreter is '/usr/bin/python3'
   288.2ms (package_name_from_spec:323): Determined package name: opi-gpio
   288.3ms (package_name_from_spec:324): Package name determined in 0.0s
   290.9ms (run_subprocess:173): running /usr/bin/python3 -m venv --without-pip /home/cristobal/.local/pipx/venvs/opi-gpio
   507.9ms (run_subprocess:186): stdout:
   508.1ms (run_subprocess:188): stderr:
   508.2ms (run_subprocess:189): returncode: 0
   509.7ms (run_subprocess:173): running /usr/bin/python3 -m venv --clear /home/cristobal/.local/pipx/shared
 11262.6ms (run_subprocess:186): stdout:
 11262.8ms (run_subprocess:188): stderr:
 11262.9ms (run_subprocess:189): returncode: 0
 11263.2ms (upgrade:91): Upgrading shared libraries in /home/cristobal/.local/pipx/shared
 11265.2ms (run_subprocess:173): running /home/cristobal/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install --force-reinstall -q --upgrade pip setuptools wheel
 22495.7ms (run_subprocess:186): stdout:
 22495.9ms (run_subprocess:188): stderr:
 22496.0ms (run_subprocess:189): returncode: 0
 22496.4ms (run_subprocess:173): running /home/cristobal/.local/pipx/venvs/opi-gpio/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
 22597.4ms (run_subprocess:186): stdout: /home/cristobal/.local/pipx/venvs/opi-gpio/lib/python3.11/site-packages
 22597.6ms (run_subprocess:189): returncode: 0
 22598.0ms (run_subprocess:173): running /home/cristobal/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
 22652.3ms (run_subprocess:186): stdout: /home/cristobal/.local/pipx/shared/lib/python3.11/site-packages
 22652.5ms (run_subprocess:189): returncode: 0
 22653.2ms (run_subprocess:173): running /home/cristobal/.local/pipx/venvs/opi-gpio/bin/python --version
 22657.8ms (run_subprocess:186): stdout: Python 3.11.2
 22658.2ms (run_subprocess:188): stderr:
 22658.3ms (run_subprocess:189): returncode: 0
 22659.1ms (_parsed_package_to_package_or_url:128): cleaned package spec: opi-gpio
 22660.6ms (run_subprocess:173): running /home/cristobal/.local/pipx/venvs/opi-gpio/bin/python -m pip install opi-gpio
 24583.1ms (run_subprocess:189): returncode: 0
 24588.4ms (run_subprocess:173): running <fetch_info_in_venv commands>
 24725.6ms (run_subprocess:186): stdout: {"sys_path": ["/usr/lib/python311.zip", "/usr/lib/python3.11", "/usr/lib/python3.11/lib-dynload", "/home/cristobal/.local/pipx/venvs/opi-gpio/lib/python3.11/site-packages", "/home/cristobal/.local/pipx/shared/lib/python3.11/site-packages"], "python_version": "3.11.2", "environment": {"implementation_name": "cpython", "implementation_version": "3.11.2", "os_name": "posix", "platform_machine": "aarch64", "platform_release": "6.12.38-current-rockchip64", "platform_system": "Linux", "platform_version": "#1 SMP PREEMPT Mon Jul 14 14:02:59 UTC 2025", "python_full_version": "3.11.2", "platform_python_implementation": "CPython", "python_version": "3.11", "sys_platform": "linux"}}
 24725.9ms (run_subprocess:189): returncode: 0
 24735.1ms (get_venv_metadata_for_package:303): get_venv_metadata_for_package: 150ms
 24735.5ms (_parsed_package_to_package_or_url:128): cleaned package spec: opi-gpio
 24736.2ms (rmdir:55): removing directory /home/cristobal/.local/pipx/venvs/opi-gpio
 24742.0ms (cli:822): PipxError: No apps associated with package opi-gpio or its dependencies. If you are attempting to install a library, pipx
should not be used. Consider using pip or a similar tool instead.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 819, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 202, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/commands/install.py", line 69, in install
    run_post_install_actions(
  File "/usr/lib/python3/dist-packages/pipx/commands/common.py", line 358, in run_post_install_actions
    raise PipxError(
pipx.util.PipxError: No apps associated with package opi-gpio or its dependencies. If you are attempting to install a library, pipx
should not be used. Consider using pip or a similar tool instead.
 24744.3ms (cli:830): pipx finished.
